### ISSUE TITLE
Move most development tools from PHIVE to Composer

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#274]
- switch all PHIVE-based tools to Composer dependencies
- update the Composer scripts to call the corresponding binary
- update the CI steps to do a `composer install` (if that's not present yet)
- update the README and explain the recommendation to use Composer for all dependencies and tools as long as there are no dependency conflicts or PHP version problems; and use PHIVE for all dev tools after that (with the exception of tools that are are dependencies of other packages, e.g., phpunit and phpstan)

**Comment by gilbertsoft** [comment]
Already posted in the channel some time ago, while looking for a way to install the dev tools with composer in a non conflicting way I've found https://github.com/bamarni/composer-bin-plugin which works good for packages available via composer. So far I've found a issue with the packages composer-normalize which is not supported as it implements composer commands. It works fine as PHAR download but this is currently not supported by composer-bin-plugin. Then I've struggled over https://github.com/LastCallMedia/ComposerExtraFiles which supports to download files including .phar but there's currently no support to get this binaries linkes to the bin folder.

So I've started a POC for solving the existing issues and closing that cap. In the end the idea is to have a collection of packages including some template packages which could be included to the project's composer.json but are installed with an extended version of composer-bin-plugin and ComposerExtraFiles without adding new dependencies to the project.

An other way I had a look at is the Symfony's phpunit-bridge which solves that problems in a similar way. But I've decided to not to go this road because it just needs to much maintenance which I like to avoid.

My current road map is to release my POC's until end of September. Therefor I've already reserved the GH Organization https://github.com/PhpDevTools where all packages get published soon. This organization should finally include everything, the base packages with the whole installtion logic and the template packages.
