### ISSUE TITLE
Drop redundant `@var` annotations

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#454]
Like here:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/74785

**Comment by linawolf** [comment]
Typed properties are only available since PHP 7.4.
As tea v2 still supports PHP 7.2 and 7.3 we cannot use typed properties and need to keep the "@var" annotations for variables.

We can, however remove` @var `annotations for methods where types are already allowed.

I searched the source code. There is no usage of` @var` annotations for methods anymore. 

Therefore I would suggest to close this ticket in favor of https://github.com/TYPO3-Documentation/tea/issues/550

**Comment by linawolf** [comment]
Sorry, accidently clicked "close" it was just meant as a suggestion
